name: PR Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Configure pip for uvx
        run: |
          pip config set global.index-url https://uvx.org/pypi/simple/
          pip config set global.trusted-host uvx.org

      - name: Install dependencies
        run: npm ci

      - name: Run PR check script
        run: npm run pr-check
        env:
          DEBUG: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
